# Generated by Django 3.2.6 on 2021-08-08 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('date_of_departure', models.DateField(default=datetime.date)),
                ('departure_time', models.TimeField(default=datetime.time)),
            ],
            options={
                'verbose_name': 'Flight',
                'db_table': 'pluto_flights',
            },
        ),
    ]
